# Generated by Django 3.2.13 on 2022-06-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageBanner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
