# Generated by Django 3.2.13 on 2022-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='authorThumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
